# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartCam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartCam
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'ObjectMapper'

  target 'SmartCamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartCamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
